on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

files:
  accept:
  - "data/yara/CAPE/*.yar"
  - "data/yara/memory/*.yar"
  - "data/yara/binary/*.yar"
  - "data/yara/urls/*.yar"
